---
sudo: required
language: objective-c
# 10.11 (see https://docs.travis-ci.com/user/osx-ci-environment/#OS-X-Version)
# osx_image: xcode7.3
osx_image: xcode8.2

before_install:
  # Uninstall existing brew installation.
  - 'ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)"'
  - rm -rf /usr/local/Homebrew -vY
  - rm -rf /usr/local/Caskroom -vY
  - rm -rf /usr/local/bin/brew -vY
  # Add rvm installation step to avoid build failure 
  # (see https://github.com/travis-ci/travis-ci/issues/5361)
  - rvm get stable --auto-dotfiles
  - rvm install 2.3.0

install:
  # Install pip.
  - sudo easy_install pip

  # Install Ansible.
  - sudo pip install ansible

  # Add ansible.cfg to pick up roles path.
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

  # Add a hosts file.
  - sudo mkdir -p /etc/ansible
  - sudo touch /etc/ansible/hosts
  - "echo -e '[local]\nlocalhost ansible_connection=local' | sudo tee -a /etc/ansible/hosts > /dev/null"

  # Add conf directory (this is an hack to pass the build)
  - sudo mkdir -p conf

script:
  # Install dependencies.
  - "ansible-galaxy install -r requirements.yml"

  # Check the role/playbook's syntax.
  - "ansible-playbook main.yml --syntax-check"

  # Test the playbook.
  - "travis_wait 30 ansible-playbook --extra-vars '{\"configure_sudoers\":\"false\"}' main.yml"

  # Test the playbook's idempotence.
  # Note that there would be 2 tasks shown as changed due to removal & recreation of the zshrc symlink
  - idempotence=$(mktemp)
  - "ansible-playbook --extra-vars '{\"configure_sudoers\":\"false\"}' main.yml | tee -a ${idempotence}"
  - >
    tail ${idempotence}
    | grep -q 'changed=2.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
