# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

pool:
  vmImage: 'macOS 10.13'

steps:


- script: |
    export ANSIBLE_INVALID_TASK_ATTRIBUTE_FAILED=False
    "echo installing ansible"
    sudo pip install ansible
    "{ echo '[defaults]'; echo 'roles_path = ../'; echo 'invalid_task_attribute_failed=false'; } >> ansible.cfg"
    sudo mkdir -p /etc/ansible
    sudo touch /etc/ansible/hosts
    # "echo -e '[local]\nlocalhost ansible_connection=local' | sudo tee -a /etc/ansible/hosts > /dev/null"
    sudo mkdir -p conf
    ansible-galaxy install -r requirements.yml
    ansible-playbook main.yml --syntax-check
    ansible-playbook main.yml
  displayName : 'Ansible playbook execution'

